version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
    ports:
      - "1433:1433"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  identityservice:
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    container_name: identityservice
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver

  productservice:
    build:
      context: .
      dockerfile: src/ProductService/Dockerfile
    container_name: productservice
    ports:
      - "5002:8080"
    depends_on:
      - mongodb
      - rabbitmq

  orderservice:
    build:
      context: .
      dockerfile: src/OrderService/Dockerfile
    ports:
      - "5003:8080"
    depends_on:
      - rabbitmq

  apigateway:
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "7250:8080"

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "5341:80"