name: CloudNativeEcommerce CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test --no-build --configuration Release

      - name: Build IdentityService Docker Image
        run: |
          docker build \
            -t cloudnativeecommerce-identityservice:latest \
            -f src/IdentityService/Dockerfile .

      - name: Build ProductService Docker Image
        run: |
          docker build \
            -t cloudnativeecommerce-productservice:latest \
            -f src/ProductService/Dockerfile .

      - name: Build OrderService Docker Image
        run: |
          docker build \
            -t cloudnativeecommerce-orderservice:latest \
            -f src/OrderService/Dockerfile .

      - name: Build ApiGateway Docker Image
        run: |
          docker build \
            -t cloudnativeecommerce-apigateway:latest \
            -f src/ApiGateway/Dockerfile .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Tag IdentityService Image
        run: |
          docker tag cloudnativeecommerce-identityservice:latest ${{ secrets.ACR_LOGIN_SERVER }}/cloudnativeecommerce-identityservice:latest

      - name: Push IdentityService Image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/cloudnativeecommerce-identityservice:latest

      - name: Tag ProductService Image
        run: |
          docker tag cloudnativeecommerce-productservice:latest ${{ secrets.ACR_LOGIN_SERVER }}/cloudnativeecommerce-productservice:latest

      - name: Push ProductService Image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/cloudnativeecommerce-productservice:latest

      - name: Tag OrderService Image
        run: |
          docker tag cloudnativeecommerce-orderservice:latest ${{ secrets.ACR_LOGIN_SERVER }}/cloudnativeecommerce-orderservice:latest

      - name: Push OrderService Image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/cloudnativeecommerce-orderservice:latest

      - name: Tag ApiGateway Image
        run: |
          docker tag cloudnativeecommerce-apigateway:latest ${{ secrets.ACR_LOGIN_SERVER }}/cloudnativeecommerce-apigateway:latest

      - name: Push ApiGateway Image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/cloudnativeecommerce-apigateway:latest